import { AI_NAME, OWNER_NAME } from "@/configuration/identity";

export const CHAT_HEADER: string = `Hello! How can I help you today?`;
export const MESSAGE_PLACEHOLDER: string = `Please wait. I am generating your answer now`;
export const FOOTER_MESSAGE: string = `Information generated by AI should only be used as a baseline resource. All information in this chat must be unclassified. This is not an official DoD resource.`;
export const CLEAR_BUTTON_TEXT: string = `Reset Chat`;
export const PAGE_TITLE: string = `Tactics and Scenario Dev`;
export const PAGE_DESCRIPTION: string = `Chat with ${AI_NAME}, ${OWNER_NAME}'s AI assistant.`;

export const EMPTY_CITATION_MESSAGE: string = "Unspecified source";
